name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: timely
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: Build project
      run: dotnet publish -c Debug -o /var/www/timely-backend
      
    - name: Restart service
      run: sudo systemctl restart kestrel-social.service
